services:
  db:
    image: postgres:latest
    env_file:
      - .env.docker
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    env_file:
      - .env.docker
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - redis
