"""Added general models of project

Revision ID: 586c81b096f0
Revises: 0a6032ea25a3
Create Date: 2026-04-09 19:35:57.045715

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "586c81b096f0"
down_revision: Union[str, Sequence[str], None] = "0a6032ea25a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mast_configs",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("height", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mast_configs_deleted_at"), "mast_configs", ["deleted_at"], unique=False
    )
    op.create_table(
        "mast_yards",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("config_id", sa.Uuid(), nullable=False),
        sa.Column("height", sa.SmallInteger(), nullable=True),
        sa.Column("amount", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["mast_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mast_yards_deleted_at"), "mast_yards", ["deleted_at"], unique=False
    )
    op.create_table(
        "complexes",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_complexes_deleted_at"), "complexes", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_complexes_is_private"), "complexes", ["is_private"], unique=False
    )
    op.create_index(op.f("ix_complexes_name"), "complexes", ["name"], unique=False)
    op.create_table(
        "measures",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("min", sa.Integer(), nullable=False),
        sa.Column("max", sa.Integer(), nullable=False),
        sa.Column("units", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measures_deleted_at"), "measures", ["deleted_at"], unique=False
    )
    op.create_table(
        "complexes_users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("complex_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["complex_id"],
            ["complexes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("complex_id", "user_id"),
    )
    op.create_table(
        "masts",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("complex_id", sa.Uuid(), nullable=False),
        sa.Column("config_id", sa.Uuid(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["complex_id"],
            ["complexes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["mast_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_masts_deleted_at"), "masts", ["deleted_at"], unique=False)
    op.create_table(
        "measure_aliases",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("measure_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["measure_id"],
            ["measures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measure_aliases_deleted_at"),
        "measure_aliases",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measure_aliases_name"), "measure_aliases", ["name"], unique=False
    )
    op.create_table(
        "measure_colors",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("measure_id", sa.Uuid(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
        sa.Column("percent", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["measure_id"],
            ["measures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measure_colors_deleted_at"),
        "measure_colors",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "roles_permissions", sa.Column("creator_id", sa.Uuid(), nullable=True)
    )
    op.drop_constraint(
        op.f("roles_permissions_added_by_fkey"), "roles_permissions", type_="foreignkey"
    )
    op.create_foreign_key(None, "roles_permissions", "users", ["creator_id"], ["id"])
    op.drop_column("roles_permissions", "added_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles_permissions",
        sa.Column("added_by", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "roles_permissions", type_="foreignkey")
    op.create_foreign_key(
        op.f("roles_permissions_added_by_fkey"),
        "roles_permissions",
        "users",
        ["added_by"],
        ["id"],
    )
    op.drop_column("roles_permissions", "creator_id")
    op.drop_index(op.f("ix_measure_colors_deleted_at"), table_name="measure_colors")
    op.drop_table("measure_colors")
    op.drop_index(op.f("ix_measure_aliases_name"), table_name="measure_aliases")
    op.drop_index(op.f("ix_measure_aliases_deleted_at"), table_name="measure_aliases")
    op.drop_table("measure_aliases")
    op.drop_index(op.f("ix_masts_deleted_at"), table_name="masts")
    op.drop_table("masts")
    op.drop_table("complexes_users")
    op.drop_index(op.f("ix_measures_deleted_at"), table_name="measures")
    op.drop_table("measures")
    op.drop_index(op.f("ix_complexes_name"), table_name="complexes")
    op.drop_index(op.f("ix_complexes_is_private"), table_name="complexes")
    op.drop_index(op.f("ix_complexes_deleted_at"), table_name="complexes")
    op.drop_table("complexes")
    op.drop_index(op.f("ix_mast_yards_deleted_at"), table_name="mast_yards")
    op.drop_table("mast_yards")
    op.drop_index(op.f("ix_mast_configs_deleted_at"), table_name="mast_configs")
    op.drop_table("mast_configs")
    # ### end Alembic commands ###
