"""Added field of prefix to masts

Revision ID: 643d2388b75b
Revises: 926057eea038
Create Date: 2026-04-27 21:51:20.152283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '643d2388b75b'
down_revision: Union[str, Sequence[str], None] = '926057eea038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masts', sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('measure_colors', 'value',
               existing_type=sa.VARCHAR(length=6),
               type_=sqlmodel.sql.sqltypes.AutoString(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measure_colors', 'value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=7),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('masts', 'prefix')
    # ### end Alembic commands ###
