"""Fixed foreign keys and relationships in many to many models

Revision ID: 89eb7cd191d3
Revises: 586c81b096f0
Create Date: 2026-04-10 16:05:14.183603

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "89eb7cd191d3"
down_revision: Union[str, Sequence[str], None] = "586c81b096f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
