"""Complex password replaced by secretkey

Revision ID: 926057eea038
Revises: c81f16062bed
Create Date: 2026-04-19 14:38:03.766952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '926057eea038'
down_revision: Union[str, Sequence[str], None] = 'c81f16062bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexes', sa.Column('secretkey', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('complexes', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexes', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('complexes', 'secretkey')
    # ### end Alembic commands ###
