"""Added access field to complex user link and other minor changes

Revision ID: aea487450710
Revises: 03039dab5506
Create Date: 2026-04-17 14:48:14.054298

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aea487450710"
down_revision: Union[str, Sequence[str], None] = "03039dab5506"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complexes_users", sa.Column("has_access", sa.Boolean(), nullable=False)
    )
    op.add_column("measures", sa.Column("creator_id", sa.Uuid(), nullable=True))
    op.drop_constraint(op.f("measures_user_id_fkey"), "measures", type_="foreignkey")
    op.create_foreign_key(None, "measures", "users", ["creator_id"], ["id"])
    op.drop_column("measures", "user_id")
    op.alter_column("users", "secondname", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "secondname", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column(
        "measures", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "measures", type_="foreignkey")
    op.create_foreign_key(
        op.f("measures_user_id_fkey"), "measures", "users", ["user_id"], ["id"]
    )
    op.drop_column("measures", "creator_id")
    op.drop_column("complexes_users", "has_access")
    # ### end Alembic commands ###
