"""Added many-to-many links for access and favorite complexes

Revision ID: c81f16062bed
Revises: aea487450710
Create Date: 2026-04-19 12:46:26.211781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c81f16062bed'
down_revision: Union[str, Sequence[str], None] = 'aea487450710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complex_accesses',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('complex_id', 'user_id')
    )
    op.create_table('complex_favorites',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('complex_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('complex_id', 'user_id')
    )
    op.drop_table('complexes_users')
    op.add_column('masts', sa.Column('rotation', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masts', 'rotation')
    op.create_table('complexes_users',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('complex_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('has_access', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], name=op.f('complexes_users_complex_id_fkey')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('complexes_users_creator_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('complexes_users_user_id_fkey')),
    sa.PrimaryKeyConstraint('complex_id', 'user_id', name=op.f('complexes_users_pkey'))
    )
    op.drop_table('complex_favorites')
    op.drop_table('complex_accesses')
    # ### end Alembic commands ###
