"""Made complex creator nullable

Revision ID: d93ffa8e11cf
Revises: 643d2388b75b
Create Date: 2026-04-28 18:20:27.971269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd93ffa8e11cf'
down_revision: Union[str, Sequence[str], None] = '643d2388b75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complexes', 'creator_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complexes', 'creator_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
